#!/usr/bin/bash
#  ______      ____
# /_  __/___  / __ \____ _      __
#  / / / __ \/ /_/ / __ \ | /| / /
# / / / /_/ / ____/ /_/ / |/ |/ /
#/_/  \____/_/    \____/|__/|__/
#
# save layouts for herbstluftwm

LAY=`herbstclient dump`
ENT=`echo "herbstclient load '$LAY'"` 

FI=`zenity --entry --title="Save the current Layout" --text="Enter name of new Layout:" --entry-text "NewLayout"`

echo "$ENT" > ~/.config/herbstluftwm/layouts/$FI 
